    AWSTemplateFormatVersion: '2010-09-09'
    Description: Static Website Hosting using S3

    Resources:

    MyWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: muni-bucket-demo   # change this (must be unique)
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

    BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
        Bucket: !Ref MyWebsiteBucket
        PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MyWebsiteBucket
                - '/*'

     Outputs:
      WebsiteURL:
       Value: !GetAtt MyWebsiteBucket.WebsiteURL
       Description: URL of the static website
